<?php 

if (function_exists('acf_add_local_field_group')) {
    acf_add_local_field_group(array(
    'key' => 'group_5e1d8f163f200',
    'title' => __('Modularity Contact Banner', 'modularity-contact-banner'),
    'fields' => array(
        0 => array(
            'key' => 'field_5e1d90c31ee10',
            'label' => __('Main content', 'modularity-contact-banner'),
            'name' => 'mod_contactbanner_main_content',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        1 => array(
            'key' => 'field_5e1e26c283a52',
            'label' => __('Header - Business hours', 'modularity-contact-banner'),
            'name' => 'mod_contactbanner_header_business_hours',
            'type' => 'text',
            'instructions' => __('Enter business hours header', 'modularity-contact-banner'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        2 => array(
            'key' => 'field_5e1e28733a316',
            'label' => __('Abnormalities - Business hours', 'modularity-contact-banner'),
            'name' => 'mod_contactbanner_abnormalities_business_hours',
            'type' => 'text',
            'instructions' => __('Enter business hours abnormalities', 'modularity-contact-banner'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        3 => array(
            'key' => 'field_5e1e309814335',
            'label' => __('Hours list', 'modularity-contact-banner'),
            'name' => 'mod_contactbanner_hours_list',
            'type' => 'repeater',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'collapsed' => '',
            'min' => 0,
            'max' => 0,
            'layout' => 'row',
            'button_label' => __('Add business weekdays and hours', 'modularity-contact-banner'),
            'sub_fields' => array(
                0 => array(
                    'key' => 'field_5e1e315214337',
                    'label' => __('Weekdays', 'modularity-contact-banner'),
                    'name' => 'mod_contactbanner_weekdays',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                1 => array(
                    'key' => 'field_5e1e318814338',
                    'label' => __('Hours from', 'modularity-contact-banner'),
                    'name' => 'mod_contactbanner_hours_from',
                    'type' => 'time_picker',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'display_format' => 'H:i',
                    'return_format' => 'H:i',
                ),
                2 => array(
                    'key' => 'field_5e1e31bf14339',
                    'label' => __('Hours to', 'modularity-contact-banner'),
                    'name' => 'mod_contactbanner_hours_to',
                    'type' => 'time_picker',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'display_format' => 'H:i',
                    'return_format' => 'H:i',
                ),
            ),
        ),
    ),
    'location' => array(
        0 => array(
            0 => array(
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'mod-contact-banner',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
));
}