<?php 

if (function_exists('acf_add_local_field_group')) {
    acf_add_local_field_group(array(
    'key' => 'group_5e1d8f163f200',
    'title' => __('Modularity Contact Banner', 'modularity-contact-banner'),
    'fields' => array(
        0 => array(
            'key' => 'field_5e1ed6113cdb8',
            'label' => __('Call to action icon list', 'modularity-contact-banner'),
            'name' => 'mod_contactbanner_cta_list',
            'type' => 'repeater',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'collapsed' => '',
            'min' => 3,
            'max' => 4,
            'layout' => 'block',
            'button_label' => __('Add item', 'modularity-contact-banner'),
            'sub_fields' => array(
                0 => array(
                    'key' => 'field_5e1ed6a13cdb9',
                    'label' => __('Title', 'modularity-contact-banner'),
                    'name' => 'mod_contactbanner_cta_title',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                1 => array(
                    'key' => 'field_5e1ed6cd3cdba',
                    'label' => __('Icon', 'modularity-contact-banner'),
                    'name' => 'mod_contactbanner_cta_icon',
                    'type' => 'text',
                    'instructions' => __('You can find the icons we use at following address:
http://v2.styleguide.helsingborg.se/icons

Just click the icon to copy or copy the icon name and paste the icon name here.', 'modularity-contact-banner'),
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                2 => array(
                    'key' => 'field_5e1ed7603cdbb',
                    'label' => __('Content', 'modularity-contact-banner'),
                    'name' => 'mod_contactbanner_cta_content',
                    'type' => 'wysiwyg',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'tabs' => 'all',
                    'toolbar' => 'full',
                    'media_upload' => 1,
                    'delay' => 0,
                ),
                3 => array(
                    'key' => 'field_5e1ed76b3cdbc',
                    'label' => __('Label - Call to action', 'modularity-contact-banner'),
                    'name' => 'mod_contactbanner_cta_label',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                4 => array(
                    'key' => 'field_5e1ed8323cdbd',
                    'label' => __('URL - Call to action', 'modularity-contact-banner'),
                    'name' => 'mod_contactbanner_cta_url',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                5 => array(
                    'key' => 'field_5e1ee12b3cdbe',
                    'label' => __('onClick - Call to action', 'modularity-contact-banner'),
                    'name' => 'mod_contactbanner_cta_onclick',
                    'type' => 'text',
                    'instructions' => __('Enter javascript', 'modularity-contact-banner'),
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
            ),
        ),
    ),
    'location' => array(
        0 => array(
            0 => array(
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'mod-contact-banner',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
));
}